controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [
      torso_yaw,
      chest_skin_frame_fixed_joint,
      codyco_balancing_world_fixed_joint,
      neck_yaw,
      imu_frame_fixed_joint,
      eye_r_yaw,
      eye_r_pitch,
      eye_l_yaw,
      eye_l_pitch,
      l_ankle_pitch,
      l_elbow,
      l_ankle_roll,
      l_foot_dh_frame_fixed_joint,
      l_wrist_prosup,
      l_forearm_dh_frame_fixed_joint,
      l_gripper_joint,
      l_wrist_yaw,
      l_hand_dh_frame_fixed_joint,
      l_hip_pitch,
      l_hip_roll,
      l_leg_ft_sensor,
      l_knee,
      l_shoulder_pitch,
      l_shoulder_roll,
      l_shoulder_yaw,
      l_sole_joint,
      l_arm_ft_sensor,
      l_upper_arm_dh_frame_fixed_joint,
      l_hip_yaw,
      l_wrist_pitch,
      neck_pitch,
      neck_roll,
      r_ankle_pitch,
      r_elbow,
      r_ankle_roll,
      r_foot_dh_frame_fixed_joint,
      r_wrist_prosup,
      r_forearm_dh_frame_fixed_joint,
      r_gripper_joint,
      r_wrist_yaw,
      r_hand_dh_frame_fixed_joint,
      r_hip_pitch,
      r_hip_roll,
      r_leg_ft_sensor,
      r_knee,
      r_shoulder_pitch,
      r_shoulder_roll,
      r_shoulder_yaw,
      r_sole_joint,
      r_arm_ft_sensor,
      r_upper_arm_dh_frame_fixed_joint,
      r_hip_yaw,
      r_wrist_pitch,
      base_fixed_joint,
      torso_joint,
      torso_pitch,
      torso_roll,
    ]