controller_list:
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
  - name: fake_right_leg_controller
    type: $(arg execution_type)
    joints:
      - r_hip_pitch
      - r_hip_roll
      - r_hip_yaw
      - r_knee
      - r_ankle_pitch
      - r_ankle_roll
  - name: fake_left_leg_controller
    type: $(arg execution_type)
    joints:
      - l_hip_pitch
      - l_hip_roll
      - l_hip_yaw
      - l_knee
      - l_ankle_pitch
      - l_ankle_roll
  - name: fake_head_controller
    type: $(arg execution_type)
    joints:
      - neck_pitch
      - neck_roll
      - neck_yaw
  - name: fake_right_eye_controller
    type: $(arg execution_type)
    joints:
      - eye_r_yaw
      - eye_r_pitch
  - name: fake_left_eye_controller
    type: $(arg execution_type)
    joints:
      - eye_l_yaw
      - eye_l_pitch
initial:  # Define initial robot poses.
  - group: right_arm
    pose: Stand
  - group: left_arm
    pose: Stand
  - group: right_leg
    pose: Stand
  - group: left_leg
    pose: Stand