controller_list:
  - name: fake_Head_controller
    type: $(arg execution_type)
    joints:
      - neck_pitch
      - neck_roll
      - neck_yaw
  - name: fake_LeftEye_controller
    type: $(arg execution_type)
    joints:
      - eye_l_yaw
      - eye_l_pitch
  - name: fake_RightEye_controller
    type: $(arg execution_type)
    joints:
      - eye_r_yaw
      - eye_r_pitch
  - name: fake_LeftArm_controller
    type: $(arg execution_type)
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
  - name: fake_RightArm_controller
    type: $(arg execution_type)
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
  - name: fake_LeftLeg_controller
    type: $(arg execution_type)
    joints:
      - l_hip_pitch
      - l_hip_roll
      - l_hip_yaw
      - l_knee
      - l_ankle_pitch
      - l_ankle_roll
  - name: fake_RightLeg_controller
    type: $(arg execution_type)
    joints:
      - r_hip_pitch
      - r_hip_roll
      - r_hip_yaw
      - r_knee
      - r_ankle_pitch
      - r_ankle_roll
initial:  # Define initial robot poses.
  - group: Head
    pose: Neutral