# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: Head
  joint_model_group_pose: Neutral
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - l_hip_pitch
    - l_hip_roll
    - l_hip_yaw
    - l_knee
    - l_ankle_pitch
    - l_ankle_roll
    - r_hip_pitch
    - r_hip_roll
    - r_hip_yaw
    - r_knee
    - r_ankle_pitch
    - r_ankle_roll
    - torso_pitch
    - torso_roll
    - torso_yaw
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow
    - l_wrist_prosup
    - l_wrist_pitch
    - l_wrist_yaw
    - neck_pitch
    - neck_roll
    - neck_yaw
    - eye_l_yaw
    - eye_l_pitch
    - eye_r_yaw
    - eye_r_pitch
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow
    - r_wrist_prosup
    - r_wrist_pitch
    - r_wrist_yaw
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: Head_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - neck_pitch
      - neck_roll
      - neck_yaw
  - name: LeftEye_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - eye_l_yaw
      - eye_l_pitch
  - name: RightEye_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - eye_r_yaw
      - eye_r_pitch
  - name: LeftArm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
  - name: RightArm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
  - name: LeftLeg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l_hip_pitch
      - l_hip_roll
      - l_hip_yaw
      - l_knee
      - l_ankle_pitch
      - l_ankle_roll
  - name: RightLeg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r_hip_pitch
      - r_hip_roll
      - r_hip_yaw
      - r_knee
      - r_ankle_pitch
      - r_ankle_roll